"""update enums

Revision ID: 089e4888d554
Revises: 4cb04c396534
Create Date: 2026-01-24 02:25:29.302851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '089e4888d554'
down_revision: Union[str, Sequence[str], None] = '4cb04c396534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ИП', 'ТОО', name='companytype').create(op.get_bind())
    op.alter_column('companies', 'type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ИП', 'ТОО', name='companytype'),
               existing_nullable=False,
               postgresql_using='type::companytype')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['user', 'assistant'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='role')],
        enum_values_to_rename=[('USER', 'user'), ('ASSISTANT', 'assistant')],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'ASSISTANT'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='role')],
        enum_values_to_rename=[('user', 'USER'), ('assistant', 'ASSISTANT')],
    )
    op.alter_column('companies', 'type',
               existing_type=sa.Enum('ИП', 'ТОО', name='companytype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    sa.Enum('ИП', 'ТОО', name='companytype').drop(op.get_bind())
    # ### end Alembic commands ###
