"""remove currency from business plan

Revision ID: 29afc4a4fbec
Revises: 089e4888d554
Create Date: 2026-01-24 02:38:02.605725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29afc4a4fbec'
down_revision: Union[str, Sequence[str], None] = '089e4888d554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_plans', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_plans', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
