"""added country and currency to business plan

Revision ID: 2d8ec0942433
Revises: dde8ad36c174
Create Date: 2025-12-30 18:00:49.816967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8ec0942433'
down_revision: Union[str, Sequence[str], None] = 'dde8ad36c174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_plans', sa.Column('country', sa.String(length=100), nullable=False))
    op.add_column('business_plans', sa.Column('currency', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_plans', 'currency')
    op.drop_column('business_plans', 'country')
    # ### end Alembic commands ###
