"""change currency and countries to codes

Revision ID: 3d9db9d806b9
Revises: 2d8ec0942433
Create Date: 2025-12-30 18:16:56.839749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9db9d806b9'
down_revision: Union[str, Sequence[str], None] = '2d8ec0942433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_plans', 'country',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('business_plans', 'currency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_plans', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('business_plans', 'country',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
