"""add is_active to user

Revision ID: 4a3679a42a7f
Revises: 5a516bcbebc9
Create Date: 2026-02-23 13:27:14.412718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3679a42a7f'
down_revision: Union[str, Sequence[str], None] = '5a516bcbebc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Step 2: Set all NULL values to True (existing users should be active)
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    
    # Step 3: Make column non-nullable
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
