"""add_company_table_and_update_business_plan

Revision ID: 4cb04c396534
Revises: a1473fcfd0fe
Create Date: 2026-01-24 02:07:47.590954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cb04c396534'
down_revision: Union[str, Sequence[str], None] = 'a1473fcfd0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Create companies table
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('oked_codes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=True)
    
    # Step 2: Add new columns as nullable first
    op.add_column('business_plans', sa.Column('company_id', sa.Uuid(), nullable=True))
    op.add_column('business_plans', sa.Column('priority_activities', postgresql.ARRAY(sa.String()), nullable=True))
    
    # Step 3: Data migration - create default companies for users with business plans
    # Get connection for data migration
    connection = op.get_bind()
    
    # Find all unique user_ids that have business plans
    result = connection.execute(sa.text("""
        SELECT DISTINCT user_id 
        FROM business_plans
    """))
    user_ids = [row[0] for row in result]
    
    # Create a default company for each user with business plans
    import uuid
    from datetime import datetime, timezone as tz
    
    for user_id in user_ids:
        company_id = uuid.uuid4()
        now = datetime.now(tz.utc)
        
        # Create default company
        connection.execute(sa.text("""
            INSERT INTO companies (id, user_id, name, type, bin, oked_codes, created_at, updated_at)
            VALUES (:id, :user_id, :name, :type, :bin, ARRAY[]::text[], :created_at, :updated_at)
        """), {
            'id': company_id,
            'user_id': user_id,
            'name': 'Компания по умолчанию',
            'type': 'ТОО',
            'bin': '000000000000',
            'created_at': now,
            'updated_at': now
        })
        
        # Update all business plans for this user to reference the new company
        connection.execute(sa.text("""
            UPDATE business_plans 
            SET company_id = :company_id, 
                priority_activities = ARRAY[]::text[]
            WHERE user_id = :user_id
        """), {
            'company_id': company_id,
            'user_id': user_id
        })
    
    # Step 4: Make columns NOT NULL now that all rows have values
    op.alter_column('business_plans', 'company_id', nullable=False)
    op.alter_column('business_plans', 'priority_activities', nullable=False)
    
    # Step 5: Create index and foreign key
    op.create_index(op.f('ix_business_plans_company_id'), 'business_plans', ['company_id'], unique=False)
    op.create_foreign_key(None, 'business_plans', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    
    # Step 6: Drop old columns and constraints
    op.drop_index(op.f('ix_business_plans_user_id'), table_name='business_plans')
    op.drop_constraint(op.f('business_plans_user_id_fkey'), 'business_plans', type_='foreignkey')
    op.drop_column('business_plans', 'user_id')
    op.drop_column('business_plans', 'country')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_plans', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('business_plans', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'business_plans', type_='foreignkey')
    op.create_foreign_key(op.f('business_plans_user_id_fkey'), 'business_plans', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_business_plans_company_id'), table_name='business_plans')
    op.create_index(op.f('ix_business_plans_user_id'), 'business_plans', ['user_id'], unique=False)
    op.drop_column('business_plans', 'priority_activities')
    op.drop_column('business_plans', 'company_id')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
