"""add business plan submission year and participation period

Revision ID: 5a516bcbebc9
Revises: 29afc4a4fbec
Create Date: 2026-02-03 16:31:42.375587

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a516bcbebc9'
down_revision: Union[str, Sequence[str], None] = '29afc4a4fbec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get current year dynamically
    current_year = datetime.now().year
    
    # Add columns as nullable first
    op.add_column('business_plans', sa.Column('participation_period_years', sa.Integer(), nullable=True))
    op.add_column('business_plans', sa.Column('planned_submission_year', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    op.execute(
        sa.text(
            f"UPDATE business_plans SET participation_period_years = 4, planned_submission_year = {current_year} "
            "WHERE participation_period_years IS NULL OR planned_submission_year IS NULL"
        )
    )
    
    # Make columns NOT NULL
    op.alter_column('business_plans', 'participation_period_years', nullable=False)
    op.alter_column('business_plans', 'planned_submission_year', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_plans', 'planned_submission_year')
    op.drop_column('business_plans', 'participation_period_years')
    # ### end Alembic commands ###
