"""updated enum

Revision ID: 5b73b7ecb092
Revises: e4ffe4aa91ee
Create Date: 2025-12-19 17:27:03.586279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b73b7ecb092'
down_revision: Union[str, Sequence[str], None] = 'e4ffe4aa91ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ASSISTANT', name='messagerole').create(op.get_bind())
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('USER', 'ASSISTANT', name='messagerole'),
               existing_nullable=False,
               postgresql_using='role::messagerole')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagetype',
        new_values=['TEXT'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagetype',
        new_values=['text'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='type')],
        enum_values_to_rename=[],
    )
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('USER', 'ASSISTANT', name='messagerole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    sa.Enum('USER', 'ASSISTANT', name='messagerole').drop(op.get_bind())
    # ### end Alembic commands ###
