"""added tool calls to schemas

Revision ID: 9daf499650ab
Revises: ee5e2c99a969
Create Date: 2025-12-30 11:39:52.535254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9daf499650ab'
down_revision: Union[str, Sequence[str], None] = 'ee5e2c99a969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_message_id'), 'tool_calls', ['message_id'], unique=False)
    op.add_column('messages', sa.Column('parent_tool_call_id', sa.String(length=64), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'ASSISTANT', 'TOOL'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='role')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagetype',
        new_values=['TEXT', 'TOOL_CALL', 'TOOL_RESULT'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagetype',
        new_values=['TEXT'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'ASSISTANT'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='role')],
        enum_values_to_rename=[],
    )
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'parent_tool_call_id')
    op.drop_index(op.f('ix_tool_calls_message_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    # ### end Alembic commands ###
