"""add llm requests table

Revision ID: d2f6b8ab1337
Revises: 3d9db9d806b9
Create Date: 2026-01-06 17:02:03.603054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f6b8ab1337'
down_revision: Union[str, Sequence[str], None] = '3d9db9d806b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('usd_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_requests_created_at'), 'llm_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_requests_model'), 'llm_requests', ['model'], unique=False)
    op.create_index(op.f('ix_llm_requests_provider'), 'llm_requests', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_requests_user_id'), 'llm_requests', ['user_id'], unique=False)
    
    # Add is_admin column as nullable first
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Set is_admin to False for all existing users
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    # Now make the column non-nullable
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_llm_requests_user_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_provider'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_model'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_created_at'), table_name='llm_requests')
    op.drop_table('llm_requests')
    # ### end Alembic commands ###
