"""update tool call and tool response structure

Revision ID: dde8ad36c174
Revises: 9daf499650ab
Create Date: 2025-12-30 13:42:27.721086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dde8ad36c174'
down_revision: Union[str, Sequence[str], None] = '9daf499650ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_call_ref', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tool_call_ref'], ['tool_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_responses_tool_call_ref'), 'tool_responses', ['tool_call_ref'], unique=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'parent_tool_call_id')
    op.drop_column('messages', 'type')
    op.create_index(op.f('ix_tool_calls_tool_call_id'), 'tool_calls', ['tool_call_id'], unique=False)
    sa.Enum('TEXT', 'TOOL_CALL', 'TOOL_RESULT', name='messagetype').drop(op.get_bind())
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'ASSISTANT'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='messagerole',
        new_values=['USER', 'ASSISTANT', 'TOOL'],
        affected_columns=[TableReference(table_schema='public', table_name='messages', column_name='role')],
        enum_values_to_rename=[],
    )
    sa.Enum('TEXT', 'TOOL_CALL', 'TOOL_RESULT', name='messagetype').create(op.get_bind())
    op.drop_index(op.f('ix_tool_calls_tool_call_id'), table_name='tool_calls')
    op.add_column('messages', sa.Column('type', postgresql.ENUM('TEXT', 'TOOL_CALL', 'TOOL_RESULT', name='messagetype', create_type=False), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('parent_tool_call_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_tool_responses_tool_call_ref'), table_name='tool_responses')
    op.drop_table('tool_responses')
    # ### end Alembic commands ###
