"""add_business_plan_and_update_chat

Revision ID: ee5e2c99a969
Revises: 5b73b7ecb092
Create Date: 2025-12-19 18:09:35.948708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5e2c99a969'
down_revision: Union[str, Sequence[str], None] = '5b73b7ecb092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_plans_user_id'), 'business_plans', ['user_id'], unique=False)
    op.add_column('chats', sa.Column('business_plan_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_chats_business_plan_id'), 'chats', ['business_plan_id'], unique=False)
    op.create_foreign_key(None, 'chats', 'business_plans', ['business_plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_index(op.f('ix_chats_business_plan_id'), table_name='chats')
    op.drop_column('chats', 'business_plan_id')
    op.drop_index(op.f('ix_business_plans_user_id'), table_name='business_plans')
    op.drop_table('business_plans')
    # ### end Alembic commands ###
