// Country data with ISO codes and names
export interface Country {
  code: string;
  name: string;
  nameRu: string;
}

export const countries: Country[] = [
  { code: "KZ", name: "Kazakhstan", nameRu: "Казахстан" },
  { code: "UZ", name: "Uzbekistan", nameRu: "Узбекистан" },
  { code: "KG", name: "Kyrgyzstan", nameRu: "Кыргызстан" },
  { code: "TJ", name: "Tajikistan", nameRu: "Таджикистан" },
  { code: "TM", name: "Turkmenistan", nameRu: "Туркменистан" },
  { code: "RU", name: "Russia", nameRu: "Россия" },
  { code: "UA", name: "Ukraine", nameRu: "Украина" },
  { code: "BY", name: "Belarus", nameRu: "Беларусь" },
  { code: "AM", name: "Armenia", nameRu: "Армения" },
  { code: "AZ", name: "Azerbaijan", nameRu: "Азербайджан" },
  { code: "GE", name: "Georgia", nameRu: "Грузия" },
  { code: "US", name: "United States", nameRu: "США" },
  { code: "GB", name: "United Kingdom", nameRu: "Великобритания" },
  { code: "DE", name: "Germany", nameRu: "Германия" },
  { code: "FR", name: "France", nameRu: "Франция" },
  { code: "IT", name: "Italy", nameRu: "Италия" },
  { code: "ES", name: "Spain", nameRu: "Испания" },
  { code: "CN", name: "China", nameRu: "Китай" },
  { code: "JP", name: "Japan", nameRu: "Япония" },
  { code: "KR", name: "South Korea", nameRu: "Южная Корея" },
  { code: "IN", name: "India", nameRu: "Индия" },
  { code: "BR", name: "Brazil", nameRu: "Бразилия" },
  { code: "MX", name: "Mexico", nameRu: "Мексика" },
  { code: "CA", name: "Canada", nameRu: "Канада" },
  { code: "AU", name: "Australia", nameRu: "Австралия" },
  { code: "NZ", name: "New Zealand", nameRu: "Новая Зеландия" },
  { code: "TR", name: "Turkey", nameRu: "Турция" },
  { code: "SA", name: "Saudi Arabia", nameRu: "Саудовская Аравия" },
  { code: "AE", name: "United Arab Emirates", nameRu: "ОАЭ" },
  { code: "SG", name: "Singapore", nameRu: "Сингапур" },
  { code: "MY", name: "Malaysia", nameRu: "Малайзия" },
  { code: "TH", name: "Thailand", nameRu: "Таиланд" },
  { code: "ID", name: "Indonesia", nameRu: "Индонезия" },
  { code: "PH", name: "Philippines", nameRu: "Филиппины" },
  { code: "VN", name: "Vietnam", nameRu: "Вьетнам" },
  { code: "PL", name: "Poland", nameRu: "Польша" },
  { code: "NL", name: "Netherlands", nameRu: "Нидерланды" },
  { code: "BE", name: "Belgium", nameRu: "Бельгия" },
  { code: "CH", name: "Switzerland", nameRu: "Швейцария" },
  { code: "AT", name: "Austria", nameRu: "Австрия" },
  { code: "SE", name: "Sweden", nameRu: "Швеция" },
  { code: "NO", name: "Norway", nameRu: "Норвегия" },
  { code: "DK", name: "Denmark", nameRu: "Дания" },
  { code: "FI", name: "Finland", nameRu: "Финляндия" },
  { code: "IE", name: "Ireland", nameRu: "Ирландия" },
  { code: "PT", name: "Portugal", nameRu: "Португалия" },
  { code: "GR", name: "Greece", nameRu: "Греция" },
  { code: "CZ", name: "Czech Republic", nameRu: "Чехия" },
  { code: "HU", name: "Hungary", nameRu: "Венгрия" },
  { code: "RO", name: "Romania", nameRu: "Румыния" },
  { code: "BG", name: "Bulgaria", nameRu: "Болгария" },
  { code: "HR", name: "Croatia", nameRu: "Хорватия" },
  { code: "SK", name: "Slovakia", nameRu: "Словакия" },
  { code: "SI", name: "Slovenia", nameRu: "Словения" },
  { code: "LT", name: "Lithuania", nameRu: "Литва" },
  { code: "LV", name: "Latvia", nameRu: "Латвия" },
  { code: "EE", name: "Estonia", nameRu: "Эстония" },
  { code: "IL", name: "Israel", nameRu: "Израиль" },
  { code: "EG", name: "Egypt", nameRu: "Египет" },
  { code: "ZA", name: "South Africa", nameRu: "ЮАР" },
  { code: "NG", name: "Nigeria", nameRu: "Нигерия" },
  { code: "KE", name: "Kenya", nameRu: "Кения" },
  { code: "AR", name: "Argentina", nameRu: "Аргентина" },
  { code: "CL", name: "Chile", nameRu: "Чили" },
  { code: "CO", name: "Colombia", nameRu: "Колумбия" },
  { code: "PE", name: "Peru", nameRu: "Перу" },
  { code: "VE", name: "Venezuela", nameRu: "Венесуэла" },
];

